defmodule ExOAPI.Stripe.Schemas.PaymentMethodDetailsGrabpay do
  use TypedEctoSchema
  import Ecto.Changeset

  @type params :: map()

  @moduledoc """
  **:transaction_id** :: *:string*

  Unique transaction id generated by GrabPay


  """

  @primary_key false
  typed_embedded_schema do
    field(:transaction_id, :string)
  end

  @spec changeset(params()) :: Ecto.Changeset.t()
  @spec changeset(__MODULE__.t(), params()) :: Ecto.Changeset.t()
  def changeset(struct \\ %__MODULE__{}, params) do
    struct
    |> cast(params, [:transaction_id])
  end
end